### ISSUE TITLE
[Bug]: Custom Raid Timer not working 06.06.2024

### ISSUE THREAD

**Issue by CeKayOne** [refringe/CustomRaidTimes#10]
### Discord Username

cekayone

### What happened?

Hey there, it looks like that the mod is super great. Unfortunately not for me. I'm trying for 5h straight to get it working. did everything right according to your instructions. 

I even named the config file like this config.jason5

however in the launcher i aint seeing anything.... 

is there any chance that you could give me a discord call via a a screenshare and show me how to make things right ?

### SPT Version

3.8.0

### Server Log

```shell
┌───────────────────────────────────────────────────────┐
│ SPT-AKI 3.8.0                                         │
│ https://discord.sp-tarkov.com                         │
│                                                       │
│ Diese Arbeit ist kostenfrei                           │
│ Wenn Sie Geld bezahlt haben, wurden Sie betrogen      │
│ Eine kommerzielle Nutzung ist untersagt               │
└───────────────────────────────────────────────────────┘
ModLoader: 0 Server-Mods werden geladen...
Server: Startprozesse werden ausgeführt...
Datenbank wird importiert...
Datenbankimport abgeschlossen.
Profile: 66367b4a00055b9fc4cdd426 took: 1.4437000000007174ms to load.
Webserver bei http://127.0.0.1:6969 gestartet
Websocket auf ws://127.0.0.1:6969 gestartet
Der Server läuft. Schließen Sie ihn nicht, während Sie SPT spielen, Viel Spaß beim Spielen!!
```

**Comment by CeKayOne** [comment]
![Screenshot 2024-05-06 012141](https://github.com/refringe/CustomRaidTimes/assets/169002924/cf4e7b7f-2812-4c1b-92af-e8ccac75a242)

**Comment by CeKayOne** [comment]
unfortunately it is not working at all Sir.

**Comment by CeKayOne** [comment]
┌───────────────────────────────────────────────────────┐
│ SPT-AKI 3.8.0                                         │
│ https://discord.sp-tarkov.com                         │
│                                                       │
│ Diese Arbeit ist kostenfrei                           │
│ Wenn Sie Geld bezahlt haben, wurden Sie betrogen      │
│ Eine kommerzielle Nutzung ist untersagt               │
└───────────────────────────────────────────────────────┘
ModLoader: 1 Server-Mods werden geladen...
Mod: custom-raid-times Version: 1.6.0 von: Refringe geladen
Server: Startprozesse werden ausgeführt...
Datenbank wird importiert...
Datenbankimport abgeschlossen.
Profile: 66367b4a00055b9fc4cdd426 took: 1.4378999999998996ms to load.
Webserver bei http://127.0.0.1:6969 gestartet
Websocket auf ws://127.0.0.1:6969 gestartet
Der Server läuft. Schließen Sie ihn nicht, während Sie SPT spielen, Viel Spaß beim Spielen!!
Found 0 insurance packages in profile 66367b4a00055b9fc4cdd426

**Comment by CeKayOne** [comment]
Just another problem popped up. Every time I launch SPTARKOV, it launches for a second and then closes

**Comment by refringe** [comment]
Resolved in [v1.7.0](https://github.com/refringe/CustomRaidTimes/releases/tag/v1.7.0)
