### ISSUE TITLE
[Bug]: Can't exit from a raid

### ISSUE THREAD

**Issue by WagorWT** [refringe/CustomRaidTimes#4]
### Discord Username

Wagor#7007

### What happened?

Whenever im dying i keep being in the raid i was - i still can hear ambient sounds, therefore the raid results message doesn't appears and i have to shut the game, whereas when i'm exiting alive everything is fine

### SPT Version

3.6.1

### Server Log

```shell
Made a winrar with all the logs i've found. I was a scav and died ~7mins after the beginning: https://drive.google.com/file/d/1urDdVJjtBU0QCs701anYtBOOl_LmUxgY/view?usp=drive_link
```

**Comment by refringe** [comment]
I requested access to the file.

**Comment by refringe** [comment]
@WagorWT Alternatively you can paste the `user/logs/` logfile in a [pastebin](https://pastebin.com/) and then drop a link to it in here.

**Comment by WagorWT** [comment]
sorry for being so late, i thought it was available for everyone who have the link. Just have given you access

**Comment by refringe** [comment]
@WagorWT I received the file above but they appear to be the wrong log files. The log files I'm looking for are the server log files found in the `/user/logs` folder. The log files that I did skim through, I noticed that you're having a client error that has something to do with an airdrop, which this mod doesn't interact with.

Are you still experiencing this issue?

Have you tried to removed *just* this mod and see if the issue has been resolved?

**Comment by WagorWT** [comment]
Hello. i'm no longer use this mod(at least yet) as i found another that did what i wanted(spawning bots instantly after starting), nevermind. And yes, airdrops always were almost empty. I guess LootingBots might be the reason, anyway thanks for help
