### ISSUE TITLE
[Bug]: CustomRaidTimes: CONFIG_LOAD_ERROR - Could not load configuration

### ISSUE THREAD

**Issue by Spartan117II** [refringe/CustomRaidTimes#7]
### Discord Username

spartan117iv

### What happened?

I download the mod and load it and it works. I try to edit the json file to make my raid times and it says could not load configuration in red when I load the server and it doesnt work.

### SPT Version

3.8.0

### Server Log

```shell
Commit hash: 2dd4d914382657378d9cdec173039d771fe33220
Build date: 1711996199777
┌─────────────────────────────────────────┐
│ SPT-AKI 3.8.0                           │
│ https://discord.sp-tarkov.com           │
│                                         │
│ This work is free of charge             │
│ If you paid money, you were scammed     │
│ Commercial use is prohibited            │
└─────────────────────────────────────────┘
ModLoader: loading 9 server mods...
Mod: ATLAS-GEAR version: 1.1.1 by: Mighty_Condor loaded
Mod: AlgorithmicLevelProgression version: 4.0.1 by: DewardianDev loaded
Mod: friendlyPMC version: 2.0.0 by: Pit Alex loaded
Mod: BoostedMeds version: 1.0.1 by: NoNeedName loaded
Mod: LotsOfLoot version: 2.2.1 by: RainbowPC loaded
Mod: custom-raid-times version: 1.6.0 by: Refringe loaded
Mod: LiveBitcoinPrices version: 1.1.0 by: Square loaded
Mod: WTT-PackNStrap version: 1.0.3 by: GrooveypenguinX loaded
Mod: SAIN version: 2.1.12 by: zSolarint loaded
CustomRaidTimes: CONFIG_LOAD_ERROR - Could not load configuration
Server: executing startup callbacks...
Importing database...
Database import finished
Loading: A T L A S Custom Weapons & Equipment
friendlyPMC: Adding Armbands to bots...
Finished loading: LotsOfLoot
Updated bitcoin to 1311585.7142857143
[WTT-Pack 'n' Strap] Database: Loaded 16 custom items.
[WTT-Pack 'n' Strap] Database: Loading complete.
Started webserver at http://127.0.0.1:6969
Started websocket at ws://127.0.0.1:6969
Server is running, do not close while playing SPT, Happy playing!!
```

**Comment by refringe** [comment]
The CONFIG_LOAD_ERROR error happens when the program can not locate the configuration file. Make sure that the file is named `config.json5`, and not `config.json5.txt`. This could easily happen if you have file extentions hidden.

![image](https://github.com/refringe/CustomRaidTimes/assets/127057/da1b82df-1db1-4a9c-9f6f-d6a5665505ec)

Also, when you're editing a file in Notepad make sure you're saving it with the "all files" type and not the "text document" type.

![image](https://github.com/refringe/CustomRaidTimes/assets/127057/726788ee-30a4-49c9-9fcd-561af24cd061)

**Comment by Swervoleopard** [comment]
worked for me, thanks !

**Comment by CeKayOne** [comment]
Hey There, i've just tried this method. And set my raids to 360 mins with weight to 1 and it still doesn't work

**Comment by refringe** [comment]
When you get the `CONFIG_LOAD_ERROR` message it means that the configuration file can not be found in the proper location:

```
config/config.json5
```

It's either been renamed incorrectly, moved, or Notepad appended a `.txt` extention to the file. There is no other explanation.
